# Generated by Django 6.0.7 on 2026-07-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='token_used',
            new_name='tokens_used',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('USER', 'Usuário'), ('AI', 'Inteligência Artificial'), ('ATTENDANT', 'Atendente')], max_length=20),
        ),
    ]
